**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

# I. NumPy.

0. Імпортувати numpy загальноприйнятим способом.

In [1]:
import numpy

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [2]:
grades = numpy.array([4, 4, 5, 3, 5, 3, 4, 4])

2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [3]:
prices = numpy.array(
    [[10, 12, 15, 60],
    [11, 14, 17, 57],
    [14, 16, 13, 74],
    [18, 20, 21, 82]]
)

3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [4]:
print("Data type of grades:", grades.dtype)
print("Data type of prices:", prices.dtype)

Data type of grades: int64
Data type of prices: int64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [5]:
print("Shape of grades:", grades.shape)
print("Shape of prices:", prices.shape)

Shape of grades: (8,)
Shape of prices: (4, 4)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [6]:
revenue = numpy.linspace(0, 1000.5, 7)
print(revenue)

[   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [7]:
first_to_stack = numpy.array([1, 2, 3, 4, 5])
second_to_stack = numpy.array([2, 4, 6, 8, 10])
print("Horizontal stack:", numpy.hstack((first_to_stack, second_to_stack)))
print("Vertical stack:", numpy.vstack((first_to_stack, second_to_stack)), sep = '\n')

Horizontal stack: [ 1  2  3  4  5  2  4  6  8 10]
Vertical stack:
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [8]:
def transpose_array(array):
    '''
    This function takes an array (either one-dimensional or multidimensional)
    and transposes it. 1D array is reshaped into a column vector.
    For multidimensional arrays, all axes are swapped.

    Input:
    array: numpy.ndarray

    Output:
    numpy.ndarray: The transposed array.
    '''

    if array.ndim == 1:
        return array.reshape(-1, 1)
    
    return array.T

print(transpose_array(numpy.array([1, 2, 3])))
print(transpose_array(numpy.array([[1, 2], [3, 4]])))

[[1]
 [2]
 [3]]
[[1 3]
 [2 4]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [9]:
first = numpy.array([[1, 2], [3, 4]])
second = numpy.array([[1, 3], [5, 7]])

print("Addition:", first + second, sep = '\n')
print("Subtraction:", first - second, sep = '\n')
print("Scalar multiplication:", first * 2, sep = '\n')
print("Multiplication:", first * second, sep = '\n')
print("Matrix multiplication:", numpy.dot(first, second), sep = '\n')

Addition:
[[ 2  5]
 [ 8 11]]
Subtraction:
[[ 0 -1]
 [-2 -3]]
Scalar multiplication:
[[2 4]
 [6 8]]
Multiplication:
[[ 1  6]
 [15 28]]
Matrix multiplication:
[[11 17]
 [23 37]]


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [11]:
matrix = numpy.array([[9, 1, 3], [7, 2, 4], [11, 4, 5]])

print("Minimal element:", numpy.min(matrix))
print("Maximal element:", numpy.max(matrix))
print("Sum of all elements:", numpy.sum(matrix))
print("Minimums for each row:", numpy.min(matrix, axis = 1))
print("Maximums for each column:", numpy.max(matrix, axis = 0))

Minimal element: 1
Maximal element: 11
Sum of all elements: 46
Minimums for each row: [1 2 4]
Maximums for each column: [11  4  5]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [49]:
repeating_matrix = numpy.array([[3, 2, 4], [3, 7, 9], [10, 4, 6]])
unique, frequencies = numpy.unique(repeating_matrix, return_counts = True)
print("Unique elements:", unique, "Frequencies:", frequencies)

Unique elements: [ 2  3  4  6  7  9 10] Frequencies: [1 2 2 1 1 1 1]


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [13]:
import pandas

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [15]:
patients = [
    {"Прізвище": "Іванов", "Ім'я": "Іван", "Дата народження": "1985-02-10", "Маса тіла": 75, "Медичне страхування": True},
    {"Прізвище": "Петренко", "Ім'я": "Олександр", "Дата народження": "1992-08-15", "Маса тіла": 82, "Медичне страхування": False},
    {"Прізвище": "Сидорова", "Ім'я": "Марія", "Дата народження": "1990-11-23", "Маса тіла": 60, "Медичне страхування": numpy.nan},
    {"Прізвище": "Ковальчук", "Ім'я": "Анна", "Дата народження": "1988-03-05", "Маса тіла": 70, "Медичне страхування": True}
]

patients_dataframe = pandas.DataFrame(patients)

In [16]:
print("Types:", patients_dataframe.dtypes, sep = '\n')


Types:
Прізвище               object
Ім'я                   object
Дата народження        object
Маса тіла               int64
Медичне страхування    object
dtype: object


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [20]:
missile_attacks = pandas.read_csv('missile_attacks_daily.csv')
print(missile_attacks)

            time_start          time_end               model  \
0     2025-01-18 20:00  2025-01-19 09:00      Shahed-136/131   
1     2025-01-17 19:00  2025-01-18 08:00      Shahed-136/131   
2     2025-01-16 19:00  2025-01-17 09:00      Shahed-136/131   
3     2025-01-16 19:00  2025-01-17 09:00    Iskander-M/KN-23   
4     2025-01-16 19:00  2025-01-17 09:00          Iskander-M   
...                ...               ...                 ...   
2039  2022-10-01 12:00  2022-10-01 12:00            Orlan-10   
2040        2022-09-30        2022-09-30            Orlan-10   
2041  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131   
2042        2022-09-28        2022-09-28                X-59   
2043        2022-09-28        2022-09-28  Reconnaissance UAV   

                                           launch_place  \
0         Bryansk oblast and Oryol oblast and Millerovo   
1     Primorsko-Akhtarsk and Bryansk oblast and Mill...   
2     Primorsko-Akhtarsk and Kursk oblast and Bryans..

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [21]:
print(missile_attacks.head(10))


         time_start          time_end             model  \
0  2025-01-18 20:00  2025-01-19 09:00    Shahed-136/131   
1  2025-01-17 19:00  2025-01-18 08:00    Shahed-136/131   
2  2025-01-16 19:00  2025-01-17 09:00    Shahed-136/131   
3  2025-01-16 19:00  2025-01-17 09:00  Iskander-M/KN-23   
4  2025-01-16 19:00  2025-01-17 09:00        Iskander-M   
5  2025-01-15 20:00  2025-01-16 09:00    Shahed-136/131   
6  2025-01-15 06:00  2025-01-15 08:00         X-59/X-69   
7  2025-01-15 06:00  2025-01-15 08:00         X-22/X-32   
8  2025-01-15 06:00  2025-01-15 08:00       X-101/X-555   
9  2025-01-15 06:00  2025-01-15 08:00            Kalibr   

                                        launch_place       target  carrier  \
0      Bryansk oblast and Oryol oblast and Millerovo      Ukraine      NaN   
1  Primorsko-Akhtarsk and Bryansk oblast and Mill...      Ukraine      NaN   
2  Primorsko-Akhtarsk and Kursk oblast and Bryans...      Ukraine      NaN   
3                 Bryansk oblast and V

14. Отримайте інформацію про форму датафрейму.

In [22]:
print("Shape of the dataframe:", missile_attacks.shape)


Shape of the dataframe: (2044, 16)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [24]:
missile_attacks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2044 entries, 0 to 2043
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2044 non-null   object 
 1   time_end              2044 non-null   object 
 2   model                 2044 non-null   object 
 3   launch_place          1023 non-null   object 
 4   target                2016 non-null   object 
 5   carrier               225 non-null    object 
 6   launched              2041 non-null   float64
 7   destroyed             2044 non-null   int64  
 8   not_reach_goal        157 non-null    float64
 9   cross_border_belarus  32 non-null     float64
 10  back_russia           34 non-null     float64
 11  still_attacking       28 non-null     float64
 12  destroyed_details     294 non-null    object 
 13  launched_details      4 non-null      object 
 14  launch_place_details  4 non-null      object 
 15  source               

16. Отримайте статистику для колонок числового типу.

In [35]:
print("Info about the numerical data:", missile_attacks.describe(), sep = '\n')

Info about the numerical data:
          launched    destroyed  not_reach_goal  cross_border_belarus  \
count  2041.000000  2044.000000      157.000000             32.000000   
mean     10.609995     7.491683       20.828025              2.312500   
std      21.041038    14.190972       19.877245              2.054696   
min       1.000000     0.000000        1.000000              1.000000   
25%       1.000000     1.000000        4.000000              1.000000   
50%       2.000000     1.000000       16.000000              2.000000   
75%       9.000000     7.000000       30.000000              2.000000   
max     193.000000    99.000000      105.000000             10.000000   

       back_russia  still_attacking  
count    34.000000        28.000000  
mean      2.000000         2.821429  
std       1.154701         2.931989  
min       1.000000         1.000000  
25%       1.000000         1.000000  
50%       2.000000         1.000000  
75%       3.000000         4.000000  
max    

17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [36]:
unique_counts = missile_attacks.nunique()
min_unique_column = unique_counts.idxmin()
min_unique_counts = missile_attacks[min_unique_column].value_counts()

In [40]:
print(unique_counts)
print("Values ​​in the column that has the least number of unique values:", min_unique_counts, sep = '\n')

time_start               864
time_end                1015
model                     61
launch_place             135
target                    97
carrier                   58
launched                 113
destroyed                 81
not_reach_goal            55
cross_border_belarus       7
back_russia                5
still_attacking            8
destroyed_details        290
launched_details           4
launch_place_details       4
source                   960
dtype: int64
Values ​​in the column that has the least number of unique values:
launched_details
{'X-101/X-555': 50, 'Kalibr': 12}                     1
{'X-101/X-555': 55, 'Kalibr': 24, 'Iskander-K': 7}    1
{'X-101/X-555': 57, 'Kalibr': 28}                     1
{'X-101/X-555': 77, 'Kalibr': 28, 'X-59/X-69': 10}    1
Name: count, dtype: int64


18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

1.   У колонках launch_place, target, carrier, not_reach_goal, cross_border_belarus, back_russia, still_attacking, destroyed_details, launched_details та launch_place_details спостерігаються значні кількості пропущених значень. Можна реструктурувати таблицю або розбити її на декілька менших.
2.   Колонки time_start та time_end мають неоднозначний формат, що ускладнює роботу з даними.

# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [41]:
missile_attacks['launched'] = missile_attacks['launched'].fillna(0)
missile_attacks['launched'] = missile_attacks['launched'].astype('Int64')

In [42]:
print(missile_attacks['launched'].dtypes)

Int64


20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [43]:
threshold = 0.3 * len(missile_attacks)
missile_attacks = missile_attacks.loc[:, missile_attacks.notnull().sum() >= threshold]

In [44]:
missile_attacks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2044 entries, 0 to 2043
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   time_start    2044 non-null   object
 1   time_end      2044 non-null   object
 2   model         2044 non-null   object
 3   launch_place  1023 non-null   object
 4   target        2016 non-null   object
 5   launched      2044 non-null   Int64 
 6   destroyed     2044 non-null   int64 
 7   source        2044 non-null   object
dtypes: Int64(1), int64(1), object(6)
memory usage: 129.9+ KB


21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [45]:
initial_count = missile_attacks.shape[0]

missile_attacks['time_start'] = pandas.to_datetime(missile_attacks['time_start'], format = "mixed")
missile_attacks['time_end'] = pandas.to_datetime(missile_attacks['time_end'], format = "mixed")
missile_attacks['duration'] = (missile_attacks['time_end'] - missile_attacks['time_start']).dt.total_seconds()

missile_attacks = missile_attacks.drop_duplicates()
missile_attacks = missile_attacks[missile_attacks['duration'] > 0]

missile_attacks.reset_index(drop = True, inplace = True)

final_count = missile_attacks.shape[0]

print("Number of deleted rows:", initial_count - final_count)



Number of deleted rows: 836


**місце для текстової відповіді**

Щоб знайти кількість видалених рядків, необхідно зафіксувати їх кількість до і після перетворення, а потім від початкової кількості відняти кінцеву.

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [46]:
print(missile_attacks[missile_attacks.isnull().any(axis = 1)])

              time_start            time_end                   model  \
25   2025-01-03 12:00:00 2025-01-03 20:00:00               X-59/X-69   
27   2025-01-03 12:00:00 2025-01-03 20:00:00              Iskander-M   
28   2025-01-03 12:00:00 2025-01-03 20:00:00                   C-300   
45   2024-12-25 05:00:00 2024-12-25 10:00:00  X-101/X-555 and Kalibr   
64   2024-12-14 19:00:00 2024-12-15 08:30:00                   C-300   
...                  ...                 ...                     ...   
1203 2022-10-06 09:00:00 2022-10-06 11:30:00               Mohajer-6   
1204 2022-10-06 00:00:00 2022-10-06 02:00:00          Shahed-136/131   
1205 2022-10-05 00:00:00 2022-10-05 02:00:00          Shahed-136/131   
1206 2022-10-02 00:00:00 2022-10-02 02:00:00          Shahed-136/131   
1207 2022-09-29 23:00:00 2022-09-29 23:59:00          Shahed-136/131   

     launch_place                            target  launched  destroyed  \
25            NaN             Dnipropetrovsk oblast        